public without sharing class ContactTriggerHelper {
    public ContactTriggerHelper() {
        //System.debug('Inside ContactTriggerHelper Constructor');
    }
    public void doTask1() {
        //System.debug('Inside Task 1');
    }
    public void doTask2() {
        //System.debug('Inside Task 2');
    }
    public void doTask3() {
        //System.debug('Inside Task 3');
    }
    public void doTask4() {
        //System.debug('Inside Task 4');
    }
    public void doTask5() {
        //System.debug('Inside Task 5');
    }

    /*public void firstLastNameDissimilarity(List<Contact> newConRecords ){
        for(Contact con: newConRecords){
            if(con.HomePhone == con.Phone){
                con.addError('Home Phone & Phone can\'t be same');
            }
        }
    }*/
}